
package com.fym.lta.UI;

import com.fym.lta.BAO.BaoFactory;
import com.fym.lta.BAO.BuildinBao;
import com.fym.lta.DAO.BuildingDao;
import com.fym.lta.DAO.DaoFactory;
import com.fym.lta.DTO.BuildingDto;

import java.awt.event.KeyEvent;

import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Islam
 */
public class BuildingPanel extends javax.swing.JPanel {

    /** Creates new form BuildingJPanel */
    public BuildingPanel() {
        try{
        initComponents();
            BuildinBao build;
            build = new BaoFactory().createBuildingBao();
            setTableModel(build.ListAll());  
        }catch (Exception e) {
                    e.printStackTrace();
                }

    }
    /** Creates new form EmpMainFram */
    private void setTableModel(List<BuildingDto> builds){
        int size=0;
        if(builds != null && !builds.isEmpty()){
            size = builds.size();
            }
        Object [][] buildArr = new Object [size][3];
        for(int i =0;i<size;i++){
            buildArr[i][0] = builds.get(i).getId();
            buildArr[i][1] = builds.get(i).getCode();
            buildArr[i][2] = builds.get(i).getDescription();
        }
        BuildTable.setModel(new javax.swing.table.DefaultTableModel(buildArr,
            new String [] {
                "Id", "Code", "Description"
            }
        ));
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        NameLabel = new javax.swing.JLabel();
        IdText = new javax.swing.JTextField();
        CodeText = new javax.swing.JTextField();
        DesText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BuildTable = new javax.swing.JTable();
        Nwe = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        SearchText = new javax.swing.JTextField();
        IdLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CodeLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setText("Description");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        IdText.setText("Enter The ID");
        IdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IdTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IdTextFocusLost(evt);
            }
        });
        add(IdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 466, -1));

        CodeText.setText("Enter The Code");
        CodeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CodeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CodeTextFocusLost(evt);
            }
        });
        add(CodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 466, -1));

        DesText.setText("Enter The Description");
        DesText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DesTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DesTextFocusLost(evt);
            }
        });
        add(DesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 466, -1));

        BuildTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Code", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BuildTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuildTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(BuildTable);
        if (BuildTable.getColumnModel().getColumnCount() > 0) {
            BuildTable.getColumnModel().getColumn(0).setHeaderValue("Id");
            BuildTable.getColumnModel().getColumn(1).setHeaderValue("Code");
            BuildTable.getColumnModel().getColumn(2).setHeaderValue("Description");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 55, 539, 274));

        Nwe.setText("New");
        Nwe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NweActionPerformed(evt);
            }
        });
        add(Nwe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 77, -1));

        Delete.setText("Delete ");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 78, -1));

        Save.setText("Update");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 81, -1));

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 75, -1));

        SearchText.setText("What do you want to search ?");
        SearchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchTextFocusLost(evt);
            }
        });
        add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 24, 448, -1));

        IdLabel.setText("Id");
        add(IdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 10, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 23, 75, -1));

        CodeLabel.setText("Code");
        add(CodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
    }//GEN-END:initComponents

    private void IdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdTextFocusGained
        // TODO add your handling code here:
        if(IdText.getText().equalsIgnoreCase("Enter The Id")){
            IdText.setText("");
        }
    }//GEN-LAST:event_IdTextFocusGained

    private void IdTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdTextFocusLost
        // TODO add your handling code here:
        if(IdText.getText().trim().equalsIgnoreCase("")){
            IdText.setText("Enter The Id");
        }
    }//GEN-LAST:event_IdTextFocusLost

    private void CodeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodeTextFocusGained
        // TODO add your handling code here:
        if(CodeText.getText().equalsIgnoreCase("Enter The Code")){
            CodeText.setText("");}
    }//GEN-LAST:event_CodeTextFocusGained

    private void CodeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodeTextFocusLost
        // TODO add your handling code here:
        if(CodeText.getText().trim().equalsIgnoreCase("")){
            CodeText.setText("Enter The Code");}
    }//GEN-LAST:event_CodeTextFocusLost

    private void DesTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DesTextFocusGained
        // TODO add your handling code here:
        if(DesText.getText().equalsIgnoreCase("Enter The Description")){
            DesText.setText("");}
    }//GEN-LAST:event_DesTextFocusGained

    private void DesTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DesTextFocusLost
        // TODO add your handling code here:
        if(DesText.getText().trim().equalsIgnoreCase("")){
            DesText.setText("Enter The Description");   }                                                                   
    }//GEN-LAST:event_DesTextFocusLost

    private void NweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NweActionPerformed
        // TODO add your handling code here:
        try{
            if(checkValidity()){
            BuildingDto b = new BuildingDto();
            BuildinBao build = new BaoFactory().createBuildingBao();
            BuildingDao bdao = new DaoFactory().createBuildingDao();
            b.setCode(CodeText.getText());
            b.setId(Integer.parseInt(IdText.getText()));
            b.setDescription(DesText.getText());
            
            if(build.insert(b)){
                JOptionPane.showMessageDialog(this, "Building Saved Successfully");
                setTableModel(bdao.viewAll());
                BuildTable.repaint();
            }
            else{
                JOptionPane.showMessageDialog(this, "The Building is already exist");
                BuildTable.repaint();
            }}
                IdText.setText("Enter The ID");
                CodeText.setText("Enter The Code");
                DesText.setText("Enter The Description");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_NweActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try{
            if(BuildTable.getSelectedRowCount()==1)
            {
                BuildingDto b = new BuildingDto();
                BuildingDao bdao;
                bdao = new DaoFactory().createBuildingDao();
                BuildinBao build = new BaoFactory().createBuildingBao();
                String s = (String) BuildTable.getValueAt(BuildTable.getSelectedRow(), 1);
                b.setCode(s);
                if(build.delete(b))
                {
                    JOptionPane.showMessageDialog(this, "Building Deleted Successfully");
                }
                setTableModel(bdao.viewAll());
                BuildTable.repaint();
            }else{
                JOptionPane.showMessageDialog(this, "Please Select Building in table ");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        try{
            if(checkValidity()){
            BuildingDto b = new BuildingDto();
            BuildinBao build = new BaoFactory().createBuildingBao();
            BuildingDao bdao = new DaoFactory().createBuildingDao();
            b.setCode(CodeText.getText());
            b.setId(Integer.parseInt(IdText.getText()));
            b.setDescription(DesText.getText());
            if(build.update(b)){
                JOptionPane.showMessageDialog(this, "Building updated Successfully");
                setTableModel(bdao.viewAll());
                BuildTable.repaint();
            }else{
                JOptionPane.showMessageDialog(this, "The Building is not exist");
                BuildTable.repaint();
            }}
            IdText.setText("Enter The ID");
            CodeText.setText("Enter The Code");
            DesText.setText("Enter The Description");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        try{
            BuildingDao build;
            build = new DaoFactory().createBuildingDao();
            setTableModel(build.viewAll());
            BuildTable.repaint();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void SearchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchTextFocusGained
        // TODO add your handling code here:
        if(SearchText.getText().equalsIgnoreCase("What do you want to search ?")){
            SearchText.setText("");}
    }//GEN-LAST:event_SearchTextFocusGained

    private void SearchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchTextFocusLost
        // TODO add your handling code here:
        if(SearchText.getText().trim().equalsIgnoreCase("")){
            SearchText.setText("What do you want to search ?");}
    }//GEN-LAST:event_SearchTextFocusLost
// Search Button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            BuildingDto b = new BuildingDto();
            List<BuildingDto> buildss = null;
            BuildingDao bdao = new DaoFactory().createBuildingDao();
            BuildinBao build = new BaoFactory().createBuildingBao();
            b.setSearch(SearchText.getText());
            buildss = build.searchFor(b);

            if(buildss!=null){
                JOptionPane.showMessageDialog(this, "Building Found");
                setTableModel(buildss);
                BuildTable.repaint();
            }else{
                JOptionPane.showMessageDialog(this, "Building is not Exist");
                setTableModel(bdao.viewAll());
                BuildTable.repaint();
            }
            SearchText.setText("What do you want to search ?");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuildTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuildTableKeyPressed
        

        
    }//GEN-LAST:event_BuildTableKeyPressed
    
    
    private boolean checkValidity(){

        // check input 1
        try{
            if(IdText.getText().equalsIgnoreCase("Enter The ID")){
                JOptionPane.showMessageDialog(this, "Please, enter id number","",JOptionPane.ERROR_MESSAGE);
                return false;            
            }
            Integer.parseInt(IdText.getText());
           // return true;
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ID is invalid! \n (please enter a number)");
                     // own implemented dialog
            return false;
        }
        try{
            if(CodeText.getText().equalsIgnoreCase("Enter The Code")){
                JOptionPane.showMessageDialog(this, "Please, enter code");
                return false;
            }
                Integer.parseInt(CodeText.getText());
                JOptionPane.showMessageDialog(this, "Code is invalid! \n (please enter a string)");
                return false;
            }catch (NumberFormatException e){
                         // own implemented dialog
                
        try{
            if(DesText.getText().equalsIgnoreCase("Enter The Description")){
                JOptionPane.showMessageDialog(this, "Please, enter description");
                return false;
            }
                Integer.parseInt(DesText.getText());
                JOptionPane.showMessageDialog(this, "Description is invalid! \n (please enter a string)");
                return false;
            }catch (NumberFormatException es){
                         // own implemented dialog
              //  return true;
        return true;
    }}}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BuildTable;
    private javax.swing.JLabel CodeLabel;
    private javax.swing.JTextField CodeText;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DesText;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField IdText;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton Nwe;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.JTextField SearchText;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
