
package com.fym.lta.UI;

import com.fym.lta.DTO.RoleDto;
import com.fym.lta.DTO.UserDto;

import java.awt.Color;

/**
 *
 * @author Mai-AbdEltwab
 */
public class DataBasePanel extends javax.swing.JPanel
{
  @SuppressWarnings("compatibility:4012648287550807639")
  private static final long serialVersionUID = 1L;

  private static UserDto user_data;
  /** Creates new form DataBasePanel */
  public DataBasePanel(UserDto user)
  {
    user_data = user;
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    departmentManagerPanel = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    CourseButton = new javax.swing.JButton();
    StaffButton = new javax.swing.JButton();
    DepartmentButton = new javax.swing.JButton();
    equipmentManagerPanel = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    EquipmentTypeButton = new javax.swing.JButton();
    EquipSpecsButton = new javax.swing.JButton();
    EquipmentButton = new javax.swing.JButton();
    locationManagerPanel = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    LocationButton = new javax.swing.JButton();
    FloorButton = new javax.swing.JButton();
    buildingButton = new javax.swing.JButton();
    LocationTypeButton = new javax.swing.JButton();
    usersManagerPanel = new javax.swing.JPanel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    UserButton = new javax.swing.JButton();
    RoleButton = new javax.swing.JButton();
    RoleScreenButton = new javax.swing.JButton();
    EmployeeButton = new javax.swing.JButton();

    setBackground(new java.awt.Color(228, 228, 228));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    departmentManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    departmentManagerPanel.setToolTipText("");
    departmentManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_org_unit_128px.png"))); // NOI18N
    departmentManagerPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    departmentManagerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    departmentManagerPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 41));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    departmentManagerPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 42));

    CourseButton.setBackground(new java.awt.Color(255, 255, 255));
    CourseButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    CourseButton.setText("Course");
    CourseButton.setToolTipText("");
    CourseButton.setBorderPainted(false);
    CourseButton.setContentAreaFilled(false);
    CourseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    CourseButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        CourseButtonMouseMoved(evt);
      }
    });
    CourseButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        CourseButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        CourseButtonMouseExited(evt);
      }
    });
    CourseButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        CourseButtonActionPerformed(evt);
      }
    });
    departmentManagerPanel.add(CourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 40));

    StaffButton.setBackground(new java.awt.Color(255, 255, 255));
    StaffButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    StaffButton.setText("Staff");
    StaffButton.setToolTipText("");
    StaffButton.setBorderPainted(false);
    StaffButton.setContentAreaFilled(false);
    StaffButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    StaffButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        StaffButtonMouseMoved(evt);
      }
    });
    StaffButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        StaffButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        StaffButtonMouseExited(evt);
      }
    });
    StaffButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        StaffButtonActionPerformed(evt);
      }
    });
    departmentManagerPanel.add(StaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 140, 40));

    DepartmentButton.setBackground(new java.awt.Color(255, 255, 255));
    DepartmentButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    DepartmentButton.setText("Department");
    DepartmentButton.setToolTipText("");
    DepartmentButton.setBorderPainted(false);
    DepartmentButton.setContentAreaFilled(false);
    DepartmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    DepartmentButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMouseMoved(evt);
      }
      public void mouseDragged(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMouseDragged(evt);
      }
    });
    DepartmentButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMouseReleased(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        DepartmentButtonMouseExited(evt);
      }
    });
    DepartmentButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        DepartmentButtonActionPerformed(evt);
      }
    });
    departmentManagerPanel.add(DepartmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 40));

    add(departmentManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 390, 390));

    equipmentManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    equipmentManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    equipmentManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_maintenance_128px.png"))); // NOI18N
    equipmentManagerPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    equipmentManagerPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 40));

    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    equipmentManagerPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 41));

    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    equipmentManagerPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 42));

    EquipmentTypeButton.setBackground(new java.awt.Color(255, 255, 255));
    EquipmentTypeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EquipmentTypeButton.setText("Equipment type");
    EquipmentTypeButton.setToolTipText("");
    EquipmentTypeButton.setBorderPainted(false);
    EquipmentTypeButton.setContentAreaFilled(false);
    EquipmentTypeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EquipmentTypeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EquipmentTypeButtonMouseMoved(evt);
      }
    });
    EquipmentTypeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EquipmentTypeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EquipmentTypeButtonMouseExited(evt);
      }
    });
    EquipmentTypeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EquipmentTypeButtonActionPerformed(evt);
      }
    });
    equipmentManagerPanel.add(EquipmentTypeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 200, 40));

    EquipSpecsButton.setBackground(new java.awt.Color(255, 255, 255));
    EquipSpecsButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EquipSpecsButton.setText("Equipment Specification");
    EquipSpecsButton.setToolTipText("");
    EquipSpecsButton.setBorderPainted(false);
    EquipSpecsButton.setContentAreaFilled(false);
    EquipSpecsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EquipSpecsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EquipSpecsButtonMouseMoved(evt);
      }
    });
    EquipSpecsButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EquipSpecsButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EquipSpecsButtonMouseExited(evt);
      }
    });
    EquipSpecsButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EquipSpecsButtonActionPerformed(evt);
      }
    });
    equipmentManagerPanel.add(EquipSpecsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 310, 40));

    EquipmentButton.setBackground(new java.awt.Color(255, 255, 255));
    EquipmentButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EquipmentButton.setText("Equipment");
    EquipmentButton.setToolTipText("");
    EquipmentButton.setBorderPainted(false);
    EquipmentButton.setContentAreaFilled(false);
    EquipmentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EquipmentButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EquipmentButtonMouseMoved(evt);
      }
    });
    EquipmentButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EquipmentButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EquipmentButtonMouseExited(evt);
      }
    });
    EquipmentButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EquipmentButtonActionPerformed(evt);
      }
    });
    equipmentManagerPanel.add(EquipmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 40));

    add(equipmentManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 400, 400));

    locationManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    locationManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    locationManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_geo_fence_128px.png"))); // NOI18N
    locationManagerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 41));

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 42));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    locationManagerPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 40));

    LocationButton.setBackground(new java.awt.Color(255, 255, 255));
    LocationButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    LocationButton.setText("Location");
    LocationButton.setToolTipText("");
    LocationButton.setBorderPainted(false);
    LocationButton.setContentAreaFilled(false);
    LocationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    LocationButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        LocationButtonMouseMoved(evt);
      }
    });
    LocationButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        LocationButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        LocationButtonMouseExited(evt);
      }
    });
    LocationButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        LocationButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(LocationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 40));

    FloorButton.setBackground(new java.awt.Color(255, 255, 255));
    FloorButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    FloorButton.setText("Floor");
    FloorButton.setToolTipText("");
    FloorButton.setBorderPainted(false);
    FloorButton.setContentAreaFilled(false);
    FloorButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    FloorButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        FloorButtonMouseMoved(evt);
      }
    });
    FloorButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        FloorButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        FloorButtonMouseExited(evt);
      }
    });
    FloorButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        FloorButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(FloorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 140, 40));

    buildingButton.setBackground(new java.awt.Color(255, 255, 255));
    buildingButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    buildingButton.setText("Building");
    buildingButton.setToolTipText("");
    buildingButton.setBorderPainted(false);
    buildingButton.setContentAreaFilled(false);
    buildingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    buildingButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        buildingButtonMouseMoved(evt);
      }
    });
    buildingButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        buildingButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        buildingButtonMouseExited(evt);
      }
    });
    buildingButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        buildingButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(buildingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 140, 40));

    LocationTypeButton.setBackground(new java.awt.Color(255, 255, 255));
    LocationTypeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    LocationTypeButton.setText("Location type");
    LocationTypeButton.setToolTipText("");
    LocationTypeButton.setBorderPainted(false);
    LocationTypeButton.setContentAreaFilled(false);
    LocationTypeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    LocationTypeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        LocationTypeButtonMouseMoved(evt);
      }
    });
    LocationTypeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        LocationTypeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        LocationTypeButtonMouseExited(evt);
      }
    });
    LocationTypeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        LocationTypeButtonActionPerformed(evt);
      }
    });
    locationManagerPanel.add(LocationTypeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 40));

    add(locationManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 390, 400));

    usersManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
    usersManagerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    usersManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_user_group_man_woman_128px.png"))); // NOI18N
    usersManagerPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 40));

    jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 41));

    jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 42));

    jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fym/lta/Images/icons8_circled_chevron_right_filled_30px.png"))); // NOI18N
    usersManagerPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 40));

    UserButton.setBackground(new java.awt.Color(255, 255, 255));
    UserButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    UserButton.setText("Users");
    UserButton.setToolTipText("");
    UserButton.setBorderPainted(false);
    UserButton.setContentAreaFilled(false);
    UserButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    UserButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        UserButtonMouseMoved(evt);
      }
    });
    UserButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        UserButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        UserButtonMouseExited(evt);
      }
    });
    UserButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        UserButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(UserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 40));

    RoleButton.setBackground(new java.awt.Color(255, 255, 255));
    RoleButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    RoleButton.setText("User roles");
    RoleButton.setToolTipText("");
    RoleButton.setBorderPainted(false);
    RoleButton.setContentAreaFilled(false);
    RoleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    RoleButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        RoleButtonMouseMoved(evt);
      }
    });
    RoleButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        RoleButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        RoleButtonMouseExited(evt);
      }
    });
    RoleButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RoleButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(RoleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 140, 40));

    RoleScreenButton.setBackground(new java.awt.Color(255, 255, 255));
    RoleScreenButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    RoleScreenButton.setText("Role screen");
    RoleScreenButton.setToolTipText("");
    RoleScreenButton.setBorderPainted(false);
    RoleScreenButton.setContentAreaFilled(false);
    RoleScreenButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    RoleScreenButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        RoleScreenButtonMouseMoved(evt);
      }
    });
    RoleScreenButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        RoleScreenButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        RoleScreenButtonMouseExited(evt);
      }
    });
    RoleScreenButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RoleScreenButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(RoleScreenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, 40));

    EmployeeButton.setBackground(new java.awt.Color(255, 255, 255));
    EmployeeButton.setFont(new java.awt.Font("VIP Rawy Regular", 0, 24)); // NOI18N
    EmployeeButton.setText("Employees");
    EmployeeButton.setToolTipText("");
    EmployeeButton.setBorderPainted(false);
    EmployeeButton.setContentAreaFilled(false);
    EmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    EmployeeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
    {
      public void mouseMoved(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMouseMoved(evt);
      }
    });
    EmployeeButton.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mousePressed(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMousePressed(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt)
      {
        EmployeeButtonMouseExited(evt);
      }
    });
    EmployeeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        EmployeeButtonActionPerformed(evt);
      }
    });
    usersManagerPanel.add(EmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 210, 40));

    add(usersManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 390, 400));
  }//GEN-END:initComponents

  private void LocationButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LocationButtonActionPerformed
  {//GEN-HEADEREND:event_LocationButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        LocationPanel location = new LocationPanel(user_data);
        location.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(location);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_LocationButtonActionPerformed

  private void FloorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FloorButtonActionPerformed
  {//GEN-HEADEREND:event_FloorButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        FloorPanel floor = new FloorPanel(user_data);
        floor.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(floor);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_FloorButtonActionPerformed

  private void buildingButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buildingButtonActionPerformed
  {//GEN-HEADEREND:event_buildingButtonActionPerformed
    // TODO add your handling code here:

    try
      {


        BuildingPanel building = new BuildingPanel(user_data);
        building.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(building);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_buildingButtonActionPerformed

  private void LocationTypeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LocationTypeButtonActionPerformed
  {//GEN-HEADEREND:event_LocationTypeButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        LocationTypePanel locationType = new LocationTypePanel(user_data);
        locationType.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(locationType);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_LocationTypeButtonActionPerformed

  private void CourseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CourseButtonActionPerformed
  {//GEN-HEADEREND:event_CourseButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        CoursePanel course = new CoursePanel(user_data);
        course.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(course);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_CourseButtonActionPerformed

  private void StaffButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_StaffButtonActionPerformed
  {//GEN-HEADEREND:event_StaffButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        StaffPanel staff = new StaffPanel(user_data);
        staff.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(staff);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_StaffButtonActionPerformed

  private void DepartmentButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DepartmentButtonActionPerformed
  {//GEN-HEADEREND:event_DepartmentButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        DepartmentPanel department = new DepartmentPanel(user_data);
        department.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(department);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_DepartmentButtonActionPerformed

  private void DepartmentButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMouseReleased
  {//GEN-HEADEREND:event_DepartmentButtonMouseReleased
    // TODO add your handling code here:
 
  }//GEN-LAST:event_DepartmentButtonMouseReleased

  private void DepartmentButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMousePressed
  {//GEN-HEADEREND:event_DepartmentButtonMousePressed
    // TODO add your handling code here:
    DepartmentButton.setForeground(Color.RED);
  }//GEN-LAST:event_DepartmentButtonMousePressed

  private void DepartmentButtonMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMouseDragged
  {//GEN-HEADEREND:event_DepartmentButtonMouseDragged
    // TODO add your handling code here
  }//GEN-LAST:event_DepartmentButtonMouseDragged

  private void DepartmentButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMouseMoved
  {//GEN-HEADEREND:event_DepartmentButtonMouseMoved
    // TODO add your handling code here:
    DepartmentButton.setForeground(Color.blue);

  }//GEN-LAST:event_DepartmentButtonMouseMoved

  private void DepartmentButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DepartmentButtonMouseExited
  {//GEN-HEADEREND:event_DepartmentButtonMouseExited
    // TODO add your handling code here:4
    DepartmentButton.setForeground(Color.black);

  }//GEN-LAST:event_DepartmentButtonMouseExited

  private void CourseButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CourseButtonMouseExited
  {//GEN-HEADEREND:event_CourseButtonMouseExited
    // TODO add your handling code here:
    CourseButton.setForeground(Color.black);
  }//GEN-LAST:event_CourseButtonMouseExited

  private void CourseButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CourseButtonMousePressed
  {//GEN-HEADEREND:event_CourseButtonMousePressed
    // TODO add your handling code here:
    CourseButton.setForeground(Color.red);

  }//GEN-LAST:event_CourseButtonMousePressed

  private void CourseButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CourseButtonMouseMoved
  {//GEN-HEADEREND:event_CourseButtonMouseMoved
    // TODO add your handling code here:
    CourseButton.setForeground(Color.blue);

  }//GEN-LAST:event_CourseButtonMouseMoved

  private void StaffButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_StaffButtonMouseExited
  {//GEN-HEADEREND:event_StaffButtonMouseExited
    // TODO add your handling code here:
    StaffButton.setForeground(Color.black);

  }//GEN-LAST:event_StaffButtonMouseExited

  private void StaffButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_StaffButtonMousePressed
  {//GEN-HEADEREND:event_StaffButtonMousePressed
    // TODO add your handling code here:
    StaffButton.setForeground(Color.red);

  }//GEN-LAST:event_StaffButtonMousePressed

  private void StaffButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_StaffButtonMouseMoved
  {//GEN-HEADEREND:event_StaffButtonMouseMoved
    // TODO add your handling code here:
    StaffButton.setForeground(Color.blue);

  }//GEN-LAST:event_StaffButtonMouseMoved

  private void LocationTypeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationTypeButtonMousePressed
  {//GEN-HEADEREND:event_LocationTypeButtonMousePressed
    // TODO add your handling code here:
    LocationTypeButton.setForeground(Color.red);

  }//GEN-LAST:event_LocationTypeButtonMousePressed

  private void LocationTypeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationTypeButtonMouseExited
  {//GEN-HEADEREND:event_LocationTypeButtonMouseExited
    // TODO add your handling code here:
    LocationTypeButton.setForeground(Color.black);

  }//GEN-LAST:event_LocationTypeButtonMouseExited

  private void LocationTypeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationTypeButtonMouseMoved
  {//GEN-HEADEREND:event_LocationTypeButtonMouseMoved
    // TODO add your handling code here:
    LocationTypeButton.setForeground(Color.blue);

  }//GEN-LAST:event_LocationTypeButtonMouseMoved

  private void LocationButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationButtonMousePressed
  {//GEN-HEADEREND:event_LocationButtonMousePressed
    // TODO add your handling code here:
    LocationButton.setForeground(Color.red);

  }//GEN-LAST:event_LocationButtonMousePressed

  private void LocationButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationButtonMouseExited
  {//GEN-HEADEREND:event_LocationButtonMouseExited
    // TODO add your handling code here:
    LocationButton.setForeground(Color.black);

  }//GEN-LAST:event_LocationButtonMouseExited

  private void LocationButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LocationButtonMouseMoved
  {//GEN-HEADEREND:event_LocationButtonMouseMoved
    // TODO add your handling code here:
    LocationButton.setForeground(Color.blue);

  }//GEN-LAST:event_LocationButtonMouseMoved

  private void FloorButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FloorButtonMousePressed
  {//GEN-HEADEREND:event_FloorButtonMousePressed
    // TODO add your handling code here:
    FloorButton.setForeground(Color.red);

  }//GEN-LAST:event_FloorButtonMousePressed

  private void FloorButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FloorButtonMouseExited
  {//GEN-HEADEREND:event_FloorButtonMouseExited
    // TODO add your handling code here:
    FloorButton.setForeground(Color.black);

  }//GEN-LAST:event_FloorButtonMouseExited

  private void FloorButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FloorButtonMouseMoved
  {//GEN-HEADEREND:event_FloorButtonMouseMoved
    // TODO add your handling code here:
    FloorButton.setForeground(Color.blue);

  }//GEN-LAST:event_FloorButtonMouseMoved

  private void buildingButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buildingButtonMousePressed
  {//GEN-HEADEREND:event_buildingButtonMousePressed
    // TODO add your handling code here:
    buildingButton.setForeground(Color.red);

  }//GEN-LAST:event_buildingButtonMousePressed

  private void buildingButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buildingButtonMouseExited
  {//GEN-HEADEREND:event_buildingButtonMouseExited
    // TODO add your handling code here:
    buildingButton.setForeground(Color.black);

  }//GEN-LAST:event_buildingButtonMouseExited

  private void buildingButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buildingButtonMouseMoved
  {//GEN-HEADEREND:event_buildingButtonMouseMoved
    // TODO add your handling code here:
    buildingButton.setForeground(Color.blue);

  }//GEN-LAST:event_buildingButtonMouseMoved

  private void EquipmentTypeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentTypeButtonMouseMoved
  {//GEN-HEADEREND:event_EquipmentTypeButtonMouseMoved
    // TODO add your handling code here:
    EquipmentTypeButton.setForeground(Color.blue);

  }//GEN-LAST:event_EquipmentTypeButtonMouseMoved

  private void EquipmentTypeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentTypeButtonMousePressed
  {//GEN-HEADEREND:event_EquipmentTypeButtonMousePressed
    // TODO add your handling code here:
    EquipmentTypeButton.setForeground(Color.red);

  }//GEN-LAST:event_EquipmentTypeButtonMousePressed

  private void EquipmentTypeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentTypeButtonMouseExited
  {//GEN-HEADEREND:event_EquipmentTypeButtonMouseExited
    // TODO add your handling code here:
    EquipmentTypeButton.setForeground(Color.black);

  }//GEN-LAST:event_EquipmentTypeButtonMouseExited

  private void EquipmentTypeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EquipmentTypeButtonActionPerformed
  {//GEN-HEADEREND:event_EquipmentTypeButtonActionPerformed
    // TODO add your handling code here:
    try
      {

        EquipmentTypePanel equip_type = new EquipmentTypePanel(user_data);
        equip_type.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(equip_type);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EquipmentTypeButtonActionPerformed

  private void EquipSpecsButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipSpecsButtonMouseMoved
  {//GEN-HEADEREND:event_EquipSpecsButtonMouseMoved
    // TODO add your handling code here:
    EquipSpecsButton.setForeground(Color.blue);

  }//GEN-LAST:event_EquipSpecsButtonMouseMoved

  private void EquipSpecsButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipSpecsButtonMousePressed
  {//GEN-HEADEREND:event_EquipSpecsButtonMousePressed
    // TODO add your handling code here:
    EquipSpecsButton.setForeground(Color.red);

  }//GEN-LAST:event_EquipSpecsButtonMousePressed

  private void EquipSpecsButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipSpecsButtonMouseExited
  {//GEN-HEADEREND:event_EquipSpecsButtonMouseExited
    // TODO add your handling code here:
   EquipSpecsButton.setForeground(Color.black);

  }//GEN-LAST:event_EquipSpecsButtonMouseExited

  private void EquipSpecsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EquipSpecsButtonActionPerformed
  {//GEN-HEADEREND:event_EquipSpecsButtonActionPerformed
    // TODO add your handling code here:
    try
      {

        EqSpecificationPanel equip_specs = new EqSpecificationPanel(user_data);
        equip_specs.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(equip_specs);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EquipSpecsButtonActionPerformed

  private void EquipmentButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentButtonMouseMoved
  {//GEN-HEADEREND:event_EquipmentButtonMouseMoved
    // TODO add your handling code here:
    EquipmentButton.setForeground(Color.blue);

  }//GEN-LAST:event_EquipmentButtonMouseMoved

  private void EquipmentButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentButtonMousePressed
  {//GEN-HEADEREND:event_EquipmentButtonMousePressed
    // TODO add your handling code here:
    EquipmentButton.setForeground(Color.red);

  }//GEN-LAST:event_EquipmentButtonMousePressed

  private void EquipmentButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EquipmentButtonMouseExited
  {//GEN-HEADEREND:event_EquipmentButtonMouseExited
    // TODO add your handling code here:
    EquipmentButton.setForeground(Color.black);

  }//GEN-LAST:event_EquipmentButtonMouseExited

  private void EquipmentButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EquipmentButtonActionPerformed
  {//GEN-HEADEREND:event_EquipmentButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        EquipmentPanel equipment = new EquipmentPanel(user_data);
        equipment.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(equipment);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EquipmentButtonActionPerformed

  private void UserButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UserButtonMouseMoved
  {//GEN-HEADEREND:event_UserButtonMouseMoved
    // TODO add your handling code here:
    UserButton.setForeground(Color.blue);
  }//GEN-LAST:event_UserButtonMouseMoved

  private void UserButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UserButtonMousePressed
  {//GEN-HEADEREND:event_UserButtonMousePressed
    // TODO add your handling code here:
    UserButton.setForeground(Color.red);
    
  }//GEN-LAST:event_UserButtonMousePressed

  private void UserButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_UserButtonMouseExited
  {//GEN-HEADEREND:event_UserButtonMouseExited
    // TODO add your handling code here:
    UserButton.setForeground(Color.black);

  }//GEN-LAST:event_UserButtonMouseExited

  private void UserButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UserButtonActionPerformed
  {//GEN-HEADEREND:event_UserButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        UserPanel user = new UserPanel(user_data);
        user.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(user);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_UserButtonActionPerformed

  private void RoleButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleButtonMouseMoved
  {//GEN-HEADEREND:event_RoleButtonMouseMoved
    // TODO add your handling code here:
   RoleButton.setForeground(Color.blue);
  }//GEN-LAST:event_RoleButtonMouseMoved

  private void RoleButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleButtonMousePressed
  {//GEN-HEADEREND:event_RoleButtonMousePressed
    // TODO add your handling code here
    RoleButton.setForeground(Color.red);

  }//GEN-LAST:event_RoleButtonMousePressed

  private void RoleButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleButtonMouseExited
  {//GEN-HEADEREND:event_RoleButtonMouseExited
    // TODO add your handling code here:
    RoleButton.setForeground(Color.black);

  }//GEN-LAST:event_RoleButtonMouseExited

  private void RoleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RoleButtonActionPerformed
  {//GEN-HEADEREND:event_RoleButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        RolePanel user_role = new RolePanel(user_data);
        user_role.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(user_role);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_RoleButtonActionPerformed

  private void RoleScreenButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleScreenButtonMouseMoved
  {//GEN-HEADEREND:event_RoleScreenButtonMouseMoved
    // TODO add your handling code here:
    RoleScreenButton.setForeground(Color.blue);

  }//GEN-LAST:event_RoleScreenButtonMouseMoved

  private void RoleScreenButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleScreenButtonMousePressed
  {//GEN-HEADEREND:event_RoleScreenButtonMousePressed
    // TODO add your handling code here:
    RoleScreenButton.setForeground(Color.red);
  }//GEN-LAST:event_RoleScreenButtonMousePressed

  private void RoleScreenButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RoleScreenButtonMouseExited
  {//GEN-HEADEREND:event_RoleScreenButtonMouseExited
    // TODO add your handling code here:
    RoleScreenButton.setForeground(Color.black);

  }//GEN-LAST:event_RoleScreenButtonMouseExited

  private void RoleScreenButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RoleScreenButtonActionPerformed
  {//GEN-HEADEREND:event_RoleScreenButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        RoleScreenPanel role_screen = new RoleScreenPanel(user_data);
        role_screen.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(role_screen);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_RoleScreenButtonActionPerformed

  private void EmployeeButtonMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMouseMoved
  {//GEN-HEADEREND:event_EmployeeButtonMouseMoved
    // TODO add your handling code here:
    EmployeeButton.setForeground(Color.blue);

  }//GEN-LAST:event_EmployeeButtonMouseMoved

  private void EmployeeButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMousePressed
  {//GEN-HEADEREND:event_EmployeeButtonMousePressed
    // TODO add your handling code here:
    EmployeeButton.setForeground(Color.red);

  }//GEN-LAST:event_EmployeeButtonMousePressed

  private void EmployeeButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_EmployeeButtonMouseExited
  {//GEN-HEADEREND:event_EmployeeButtonMouseExited
    // TODO add your handling code here:
    EmployeeButton.setForeground(Color.black);

  }//GEN-LAST:event_EmployeeButtonMouseExited

  private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmployeeButtonActionPerformed
  {//GEN-HEADEREND:event_EmployeeButtonActionPerformed
    // TODO add your handling code here:
    try
      {


        EmployeePanel employee = new EmployeePanel(user_data);
        employee.setBounds(this.getBounds());
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(employee);


      }
    catch(Exception e)
      {
        e.printStackTrace();
      }
  }//GEN-LAST:event_EmployeeButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton CourseButton;
  public javax.swing.JButton DepartmentButton;
  public javax.swing.JButton EmployeeButton;
  public javax.swing.JButton EquipSpecsButton;
  public javax.swing.JButton EquipmentButton;
  public javax.swing.JButton EquipmentTypeButton;
  public javax.swing.JButton FloorButton;
  public javax.swing.JButton LocationButton;
  public javax.swing.JButton LocationTypeButton;
  public javax.swing.JButton RoleButton;
  public javax.swing.JButton RoleScreenButton;
  public javax.swing.JButton StaffButton;
  public javax.swing.JButton UserButton;
  public javax.swing.JButton buildingButton;
  private javax.swing.JPanel departmentManagerPanel;
  private javax.swing.JPanel equipmentManagerPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel locationManagerPanel;
  private javax.swing.JPanel usersManagerPanel;
  // End of variables declaration//GEN-END:variables

}
