package com.fym.lta.UI;

/**
 *
 * @author Nada El-Gammal
 */


import com.fym.lta.BAO.BaoFactory;
import com.fym.lta.BAO.EquipmentBao;
import com.fym.lta.BAO.EquipmentTypeBao;
import com.fym.lta.DAO.DaoFactory;
import com.fym.lta.DAO.EquipmentDao;
import com.fym.lta.DAO.EquipmentTypeDao;
import com.fym.lta.DTO.EquipmentDto;

import com.fym.lta.DTO.EquipmentTypeDto;

import java.awt.event.KeyEvent;

import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Nada El-Gammal
 */
public class EquipmentTypePanel extends java.awt.Panel {
    private EquipmentTypeBao business;

    /** Creates new form EquipmentTypePanel */
    public EquipmentTypePanel() {
        try {
                   business = new BaoFactory().createEquipmentTypeBao();
                   EquipmentTypeDao dao = new DaoFactory().createEquipmentTypeDao();
                   initComponents();
                   setTableModel(dao.viewAll());            
                   
               } catch (Exception e) {
                   e.printStackTrace();
               }    }
    
    private void setTableModel(List<EquipmentTypeDto> equipt){
            int size = 0;
            if(equipt != null && !equipt.isEmpty())
                size = equipt.size();
            
            Object [][] equipsArr = new Object [size][4];
            for(int i =0;i<size;i++){
                equipsArr[i][0] = equipt.get(i).getId();
                equipsArr[i][1] = equipt.get(i).getCode();
                equipsArr[i][2] = equipt.get(i).getName();
                equipsArr[i][3] = equipt.get(i).getNo_of_equip();

            }
            EqTypeTable.setModel(new javax.swing.table.DefaultTableModel(equipsArr,
                new String [] {
                    "Id", "Code", "Name" , "No. Of Equips"
                }
            ));    
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EqTypeTable = new javax.swing.JTable();
        codeLabel = new javax.swing.JLabel();
        codeTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        codeLabel1 = new javax.swing.JLabel();
        noOfEquipTextField1 = new javax.swing.JTextField();
        codeLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        NewButton = new javax.swing.JButton();
        listEquipmentsButton1 = new javax.swing.JButton();

        searchTextField.setText("Enter text to search");
        searchTextField.setPreferredSize(new java.awt.Dimension(74, 19));
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        EqTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Name", "No. Of Equips"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EqTypeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EqTypeTableMouseClicked(evt);
            }
        });
        EqTypeTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EqTypeTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(EqTypeTable);
        if (EqTypeTable.getColumnModel().getColumnCount() > 0) {
            EqTypeTable.getColumnModel().getColumn(0).setHeaderValue("ID");
            EqTypeTable.getColumnModel().getColumn(1).setHeaderValue("Code");
            EqTypeTable.getColumnModel().getColumn(2).setHeaderValue("Name");
            EqTypeTable.getColumnModel().getColumn(3).setHeaderValue("No. Of Equips");
        }

        codeLabel.setText("ID:");

        codeTextField.setText("Enter Code");
        codeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeTextFieldFocusLost(evt);
            }
        });
        codeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTextFieldActionPerformed(evt);
            }
        });

        idLabel.setText("No. Of Equipments:");

        IDTextField.setText("Enter ID");
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        codeLabel1.setText("Code:");

        noOfEquipTextField1.setText("Enter Number of Equipments");
        noOfEquipTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                noOfEquipTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfEquipTextField1FocusLost(evt);
            }
        });
        noOfEquipTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfEquipTextField1ActionPerformed(evt);
            }
        });

        codeLabel2.setText("Name:");

        nameTextField.setText("Enter Name");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        NewButton.setText("New");
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });

        listEquipmentsButton1.setText("List Equipments ");
        listEquipmentsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEquipmentsButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeLabel1)
                    .addComponent(codeLabel2)
                    .addComponent(codeLabel)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codeTextField)
                    .addComponent(IDTextField)
                    .addComponent(nameTextField)
                    .addComponent(noOfEquipTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listEquipmentsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel1)
                    .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfEquipTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(saveButton)
                    .addComponent(DeleteButton)
                    .addComponent(NewButton)
                    .addComponent(listEquipmentsButton1))
                .addContainerGap())
        );
    }//GEN-END:initComponents

  EquipmentTypeDto et = new EquipmentTypeDto();

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        if(searchTextField.getText().equalsIgnoreCase("Enter text to search")){
            searchTextField.setText("");
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        if(searchTextField.getText().trim().equalsIgnoreCase("")){
            searchTextField.setText("Enter text to search");
        }
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed

    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try{
            EquipmentDao e = new DaoFactory().createEquipmentDao();
            List<EquipmentTypeDto> search_list = null;
            //et.setSearch(searchTextField.getText());
            EquipmentTypeDto equipt = new EquipmentTypeDto(searchTextField.getText());
            search_list = business.searchFor(equipt);
            if( search_list !=null )
            {
                JOptionPane.showMessageDialog(this, "Equipmnet Type Found");
                setTableModel(search_list);
                EqTypeTable.repaint();
            }
            else
            {
                setTableModel(search_list);
                EqTypeTable.repaint();
            }
            searchTextField.setText("Enter text to search");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void codeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeTextFieldFocusGained
        if (codeTextField.getText().equalsIgnoreCase("Enter Code"))
        codeTextField.setText("");
    }//GEN-LAST:event_codeTextFieldFocusGained

    private void codeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeTextFieldFocusLost
        if (codeTextField.getText().trim().equalsIgnoreCase(""))
        codeTextField.setText("Enter Code");
    }//GEN-LAST:event_codeTextFieldFocusLost

    private void codeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTextFieldActionPerformed

    private void IDTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusGained
        if (IDTextField.getText().equalsIgnoreCase("Enter ID"))
        IDTextField.setText("");
    }//GEN-LAST:event_IDTextFieldFocusGained

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost
        if (IDTextField.getText().trim().equalsIgnoreCase(""))
        IDTextField.setText("Enter ID");
    }//GEN-LAST:event_IDTextFieldFocusLost

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void noOfEquipTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfEquipTextField1FocusGained
    if (noOfEquipTextField1.getText().equalsIgnoreCase("Enter Number of Equipments"))
    noOfEquipTextField1.setText("");
    }//GEN-LAST:event_noOfEquipTextField1FocusGained

    private void noOfEquipTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfEquipTextField1FocusLost
    if (noOfEquipTextField1.getText().trim().equalsIgnoreCase(""))
    noOfEquipTextField1.setText("Enter Number of Equipments");
    }//GEN-LAST:event_noOfEquipTextField1FocusLost

    private void noOfEquipTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfEquipTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfEquipTextField1ActionPerformed

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        if (nameTextField.getText().equalsIgnoreCase("Enter Name"))
        nameTextField.setText("");
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
    if (nameTextField.getText().trim().equalsIgnoreCase(""))
    nameTextField.setText("Enter Name");
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try
        {   
            if(checkValidity()){
            EquipmentTypeDao e = new DaoFactory().createEquipmentTypeDao();
            et.setId(Integer.parseInt(IDTextField.getText()));
            et.setCode(codeTextField.getText());
            et.setName(nameTextField.getText());
            et.setNo_of_equip(Integer.parseInt(noOfEquipTextField1.getText()));
            if(business.update(et)){
                JOptionPane.showMessageDialog(this, "Equipment Updated Successfully");
                setTableModel(e.viewAll());
                EqTypeTable.repaint();
            }else{
                EqTypeTable.repaint();
            }
        }
            IDTextField.setText("Enter ID");
            codeTextField.setText("Enter Code");
            nameTextField.setText("Enter Name");
            noOfEquipTextField1.setText("Enter Number of Equipments");
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error!");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try{
            EquipmentTypeDao e = new DaoFactory().createEquipmentTypeDao();
            setTableModel(e.viewAll());
            EqTypeTable.repaint();
        }
        catch(Exception e)
        { e.printStackTrace();}

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try{
            EquipmentTypeDao e = new DaoFactory().createEquipmentTypeDao();
            int row = EqTypeTable.getSelectedRow();
            et.setId(Integer.parseInt(EqTypeTable.getModel().getValueAt(row,0).toString()));
            et.setCode(EqTypeTable.getModel().getValueAt(row,1).toString());
            et.setName(EqTypeTable.getModel().getValueAt(row,2).toString());
            et.setNo_of_equip(Integer.parseInt(EqTypeTable.getModel().getValueAt(row,3).toString()));
            if(business.delete(et)){
                JOptionPane.showMessageDialog(this, "Equipment Deleted Successfully");
                setTableModel(e.viewAll());
                EqTypeTable.repaint();
            }else{
                JOptionPane.showMessageDialog(this, "Please select a Type to delete");
                EqTypeTable.repaint();
            }
            }
        catch(java.lang.ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Please select row from table to delete");
            }
        catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        try{       
            if (checkValidity()){
            EquipmentTypeDao e = new DaoFactory().createEquipmentTypeDao();
            et.setId(Integer.parseInt(IDTextField.getText()));
            et.setCode(codeTextField.getText());
            et.setName(nameTextField.getText());
            et.setNo_of_equip(Integer.parseInt(noOfEquipTextField1.getText()));
            if(business.add(et)){
                JOptionPane.showMessageDialog(this, "Equipment Inserted Successfully");
                setTableModel(e.viewAll());
                EqTypeTable.repaint();
            }else
            {
            EqTypeTable.repaint();
        }}
            IDTextField.setText("Enter ID");
            codeTextField.setText("Enter Code");
            nameTextField.setText("Enter Name");
            noOfEquipTextField1.setText("Enter Number of Equipments");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_NewButtonActionPerformed

    private void setNewTable(List<EquipmentDto> eq){
            int size = 0;
            if(eq != null && !eq.isEmpty())
                size = eq.size();
            
            Object [][] eqArr = new Object [size][4];
            for(int i =0;i<size;i++){
                eqArr[i][0] = eq.get(i).getId();
                eqArr[i][1] = eq.get(i).getCode();
                eqArr[i][2] = eq.get(i).getType().getId();
                eqArr[i][3] = eq.get(i).getCountry();

            }
            EqTypeTable.setModel(new javax.swing.table.DefaultTableModel(eqArr,
                new String [] {
                    "Id", "Code", "Type ID" , "Country"
                }
            ));    
        }

    private void listEquipmentsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEquipmentsButton1ActionPerformed
        try{ List<EquipmentDto> eq = null;        
            int row = EqTypeTable.getSelectedRow();
            et.setId(Integer.parseInt(EqTypeTable.getModel().getValueAt(row,0).toString()));
            et.setCode(EqTypeTable.getModel().getValueAt(row,1).toString());
            et.setName(EqTypeTable.getModel().getValueAt(row,2).toString());
            et.setNo_of_equip(Integer.parseInt(EqTypeTable.getModel().getValueAt(row,3).toString()));
            eq=business.loadAllEquips(et);
            if( eq!=null){
                setNewTable(eq);
                EqTypeTable.repaint();                
            }
        }
        catch(java.lang.ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Please select type from table to show its equipments");
            }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_listEquipmentsButton1ActionPerformed

    private void EqTypeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqTypeTableMouseClicked
        // TODO add your handling code here:
        int row = EqTypeTable.getSelectedRow();
        IDTextField.setText(EqTypeTable.getValueAt(row, 0).toString());
        codeTextField.setText(EqTypeTable.getValueAt(row, 1).toString());
        nameTextField.setText(EqTypeTable.getValueAt(row, 2).toString());
        noOfEquipTextField1.setText(EqTypeTable.getValueAt(row, 3).toString());
    }//GEN-LAST:event_EqTypeTableMouseClicked

    private void EqTypeTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EqTypeTableKeyPressed
        if( evt.getExtendedKeyCode()==KeyEvent.VK_UP || evt.getExtendedKeyCode()==KeyEvent.VK_DOWN ){
            int row = EqTypeTable.getSelectedRow();
            IDTextField.setText(EqTypeTable.getValueAt(row, 0).toString());
            codeTextField.setText(EqTypeTable.getValueAt(row, 1).toString());
            nameTextField.setText(EqTypeTable.getValueAt(row, 2).toString());
            noOfEquipTextField1.setText(EqTypeTable.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_EqTypeTableKeyPressed

    private boolean checkValidity(){
            try{
                if(IDTextField.getText().equalsIgnoreCase("Enter ID")){
                    JOptionPane.showMessageDialog(this, "Please, enter id number","",JOptionPane.ERROR_MESSAGE);
                    return false;            
                }
                Integer.parseInt(IDTextField.getText());
               // return true;
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "ID is invalid! \n (please enter a number)");
                         // own implemented dialog
                return false;
            }
            
            try{
                if(noOfEquipTextField1.getText().equalsIgnoreCase("Enter Number of Equipments")){
                    JOptionPane.showMessageDialog(this, "Please, enter id number","",JOptionPane.ERROR_MESSAGE);
                    return false;            
                }
                Integer.parseInt(noOfEquipTextField1.getText());
               // return true;
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Number of equipments is invalid! \n (please enter a number)");
                         // own implemented dialog
                return false;
            }
            
            try{
                if(codeTextField.getText().equalsIgnoreCase("Enter Code")){
                    JOptionPane.showMessageDialog(this, "Please, enter code");
                    return false;
                }
                    Integer.parseInt(codeTextField.getText());
                    JOptionPane.showMessageDialog(this, "Code is invalid! \n (please enter a string)");
                    return false;
                }catch (NumberFormatException e){
                             // own implemented dialog
                    
            try{
                if(nameTextField.getText().equalsIgnoreCase("Enter Name")){
                    JOptionPane.showMessageDialog(this, "Please, enter name");
                    return false;
                }
                    Integer.parseInt(nameTextField.getText());
                    JOptionPane.showMessageDialog(this, "Name is invalid! \n (please enter a string)");
                    return false;
                }catch (NumberFormatException es){
                             // own implemented dialog
                  //  return true;
            return true;
            }}
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTable EqTypeTable;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JButton NewButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel codeLabel1;
    private javax.swing.JLabel codeLabel2;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listEquipmentsButton1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField noOfEquipTextField1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables

}
